baseURL = 'https://jamesjoshuahill.github.io/'
languageCode = 'en-us'
title = 'Josh Hill'

[params]
  author = 'Josh Hill'
  description = 'Personal website'
  github = 'jamesjoshuahill'

[permalinks]
  playbook = '/playbook/:year-:month-:day-:slugorfilename/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
